### ISSUE TITLE
PROBLEMA INSTALLAZIONE AUTOMATICA SU ALTERVISTA

### ISSUE THREAD

**Issue by Faobi69** [trinko/giuaschool#109]
Buona sera, stavo provando a installare il registro su altervista per poi portarlo su aruba, utilizzando l'installazione guidato ottengo questo problema:

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_registrodemo.gs_configurazione' doesn't exist in /membri/registrodemo/giuaschool/src/Install/Installer.php:347 Stack trace: #0 /membri/registrodemo/giuaschool/src/Install/Installer.php(347): PDOStatement->execute(Array) #1 /membri/registrodemo/giuaschool/src/Install/Installer.php(322): App\Install\Installer->getParameter('versione') #2 /membri/registrodemo/giuaschool/src/Install/Installer.php(266): App\Install\Installer->init() #3 /membri/registrodemo/giuaschool/public/install/index.php(10): App\Install\Installer->run() #4 {main} thrown in /membri/registrodemo/giuaschool/src/Install/Installer.php on line 347

Qualcuno saprebbe aiutarmi a risolvere il problema?

**Comment by trinko** [comment]
Sostituisci il file **src/Install/Installer.php**  con quello allegato e riprova.

Fammi sapere se risolve il problema.
[Installer.php.zip](https://github.com/trinko/giuaschool/files/7833126/Installer.php.zip)

**Comment by Faobi69** [comment]
Si grazie, ma adesso andando avanti con l'installazione (dopo che mi viene scritta che il nuovo file .env è stato salvato correttamente) ottengo questo errore: 

`Fatal error: Uncaught Error: Failed opening required '/membri/registrodemo/giuaschool/vendor/autoload.php' (include_path='.:') in /membri/registrodemo/giuaschool/config/bootstrap.php:5 Stack trace: #0 /membri/registrodemo/giuaschool/public/install/createdb.txt(13): require() #1 /membri/registrodemo/giuaschool/src/Install/Installer.php(609): include('/membri/registr...') #2 /membri/registrodemo/giuaschool/src/Install/Installer.php(988): App\Install\Installer->createSchema() #3 /membri/registrodemo/giuaschool/src/Install/Installer.php(276): App\Install\Installer->pageCreate6() #4 /membri/registrodemo/giuaschool/public/install/index.php(10): App\Install\Installer->run() #5 {main} thrown in /membri/registrodemo/giuaschool/config/bootstrap.php on line 5`

**Comment by trinko** [comment]
Controlla se esiste il file **/membri/registrodemo/giuaschool/vendor/autoload.php**
Nel caso esista, controlla i permessi.

**Comment by Faobi69** [comment]
no non esiste proprio

**Comment by trinko** [comment]
Se non esiste, hai scaricato i file sbagliati. Devi scaricare i file della release, non quelli indicati come sorgenti.
Riporto il link dell'ultima modifica:
[release.zip](https://github.com/trinko/giuaschool/suites/4870981481/artifacts/138976060)

**Comment by Faobi69** [comment]
Grazie mille ho risolto ma ho natato la presenza di un problema:
- Quando si inseriscono gli alunni non si possono più modificare (nella tabella per la ricerca degli alunni non campere nessuno, neanche digitando nome e cognome

**Comment by trinko** [comment]
>     * Quando si inseriscono gli alunni non si possono più modificare (nella tabella per la ricerca degli alunni non campere nessuno, neanche digitando nome e cognome

Lascia in bianco i campi delle username, in modo che vengano generate automaticamente. Attualmente, se le imposti in formato diverso da quello previsto crea problemi del tipo indicato.

>     * Inoltre quando si deve aggiungere un alunno devo per forza inserire le informazioni di entrambi i genitori e se l'alunno ne ha solo uno? fare in modo che le informazioni dei genitori o del genitore 2 non siano obbligatorie

Non è necessario inserire i dati dei genitori. Lascia in bianco i dati dei genitori: gli utenti dei genitori verranno creati con dati fittizi, e puoi deciderli di non usarli.

**Comment by trinko** [comment]
> * Possibilità di impostare le valutazioni numeriche quindi scegliere se sono abilitati i voti col + o -, solo col mezzo voto e solo interi. (io per esempio non vorrei che ci fossero i + e i - ma solo voti interi o mezzi)

Ci sono docenti che preferiscono usarli e altri no: perché imporre a tutti i docenti queste limitazioni? O intendi una configurazione valida solo per il proprio utente?

> * Possibilità di scegliere il voto minimo e voto massimo assegnabile

No. La normativa sulle valutazioni è chiara: voto minimo 1 e voto massimo 10.

> * Possibilità di scegliere un numero massimo di voti inseribili per tiplogia per esempio 4+4+4 per periodo scolastico

Perché imporre un numero massimo di valutazioni? Se il docente ritiene di dover fare una valutazione in più, perché impedirglielo?

> * Possibilità da parte dei docenti di inserire il voto in qualsiasi giornata loro vogliano senza il vincolo di aver firmato una lezione in quella giornata per quella materia

No. Il voto deve essere associato ad una lezione svolta. In caso contrario, sarebbe un grave errore formale e potrebbe essere oggetto di ricorso sull'esito finale.

**Comment by Faobi69** [comment]
Capisco, grazie mille comunque, si hai ragione in merito al secondo e terzo punto ma al primo e al secondo no, io aggiungerei delle opzione nella sezione parametri dell'account amministratore in modo che ogni scuola possa decidere in consiglio di istituto quali devono essere le valutazioni utilizzabili (dato che ogni istituto è autonomo) nella mia scuola è in vigore il voto minimo 3 e voto massimo 10 e l'utilizzo dei soli voti interi e voti mezzi senza i + o i -; infatti per provare ho modificato personalmente i file html twig per adattare il registro alle esigenze, però ti chiederi di mettere un'impostazione per evitare di associare un voto a una lezione, se un docente corregge le verifiche di domenica deve per forza inserire il voto nel giorno in cui la verifica è stata svolta?
